substitutions:
  name: "name"

esphome:
  name: "${name}"
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_flash: 40000000L
    board_build.flash_size: 4MB
  on_boot:
    - priority: 500
      then:
        - esp32_ble_tracker.stop_scan:
    - priority: 100
      then:
        - delay: 10s
        - esp32_ble_tracker.start_scan:
            continuous: true

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    #type: arduino
    type: esp-idf

# Enable logging
logger:
  logs:
    esp-idf: ERROR

<<: !include secrets.yaml


esp32_ble_tracker:
  scan_parameters:
    active: true
    continuous: true

bluetooth_proxy:
  active: true

output:
  - platform: ledc
    id: output_r
    pin: GPIO10
    max_power: 80%
    min_power: 1%
    zero_means_zero: true
  - platform: ledc
    id: output_g
    pin: GPIO7
    max_power: 80%
    min_power: 1%
    zero_means_zero: true
  - platform: ledc
    id: output_b
    pin: GPIO6
    max_power: 80%
    min_power: 1%
    zero_means_zero: true
  - platform: ledc
    id: output_cw
    pin: GPIO5
    max_power: 80%
    min_power: 1%
    zero_means_zero: true
  - platform: ledc
    id: output_ww
    pin: GPIO3
    max_power: 80%
    min_power: 1%
    zero_means_zero: true

